### ISSUE TITLE
In memory image creation

### ISSUE THREAD

**Issue by aminya** [kdomanski/iso9660#18]
Currently, the package creates a temporary folder and copies the files into it to create the image. This can be avoided by using an in-memory creation.

**Comment by kdomanski** [comment]
Hi. Using a staging directory is intentional, in order to avoid a large memory footprint in case of building a larger image.
You can still do it in memory by using a memory-backed filesystem (e.g. tmpfs) for your staging directory.
Note that when possible (i.e. when the staging directory is on the same mount as the source files) the library creates a hardlink instead of copying a file.
