### ISSUE TITLE
Configurable option for disabling file renaming

### ISSUE THREAD

**Issue by AshleyEke** [kdomanski/iso9660#43]
Would it be possible to have a flag on the file writer so that if set, any files we write are not renamed to follow the correct standard? 

I am working with legacy applications that use the incorrect naming convention and will reference files on the ISO which don't exist because of the file rename. Having to change the installer and all associated files to follow the new convention would be a painful process.

**Comment by kdomanski** [comment]
For a basic ISO image the renaming is necessary, otherwise the resulting image wouldn't be valid (and might simply break in compliant readers).

What you really need is to generate an ISO image with Rock Ridge extension - that allows less restriction in naming.
The support for that has yet to be implemented. See https://github.com/kdomanski/iso9660/issues/38

**Comment by AshleyEke** [comment]
ok thank you I shall subscribe to that issue for updates.
